# Generated by Django 5.2.3 on 2025-06-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_folderaccess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FolderAccess',
            new_name='FolderAcces',
        ),
    ]
