# Generated by Django 5.2.3 on 2025-06-30 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_rename_folderaccess_folderacces'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FolderAcces',
            new_name='FolderAccess',
        ),
    ]
