# Generated by Django 5.2.3 on 2025-07-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_fileaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('development', 'Development'), ('production', 'Production')], max_length=20, unique=True)),
                ('base_url', models.URLField(help_text='Base domain URL like https://example.com')),
            ],
        ),
    ]
