# Generated by Django 5.2.3 on 2025-07-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_environmentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileaccess',
            name='can_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folderaccess',
            name='can_download',
            field=models.BooleanField(default=False),
        ),
    ]
