# Generated by Django 5.2.3 on 2025-07-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_fileaccess_is_trashed_fileaccess_last_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermissions',
            name='can_create_folder',
        ),
    ]
